class Stems:
    def __init__(self,pcd,stems):
        ...

    def relations(self):
        ...

    def __construct_triangles(self):
        ...

    def __local_matching(self):
        ...

    def __global_matching(self):
        ...